Add sensitive data encryption feature

diff --git a/sendMail b/sendMail
--- a/sendMail
+++ b/sendMail
@@ -40,15 +40,19 @@ help_info()
   echo
   echo "	${bold}-a${default} ${underline}email's username${default}, ${bold}--account${default} ${underline}email's username${default}"
   echo
-  echo "    provide the email address from which you will send your mails"
+  echo "                provide the email address from which you will send your mails"
   echo
   echo "	${bold}-c, --configure${default}"
   echo
-  echo "    when this flag is invoked, you have to provide your account (-a or --account) and password (-p or --password) command-line arguments to complete the setup"
+  echo "                when this flag is invoked, you have to provide your account (-a or --account) and password (-p or --password) command-line arguments to complete the setup"
   echo
   echo "	${bold}-d, --delete${default}"
   echo
-  echo "    the senders emails with be deleted from the .sendMail dir (found under the home directory)"
+  echo "                the senders emails with be deleted from the .sendMail dir (found under the home directory)"
+  echo
+  echo "	${bold}-e${default} ${underline}encryption password${default}, ${bold}--encryption${default} ${underline}encyrption password${default}"
+  echo
+  echo "                if using a shared machine, it is highly recommended to encrypt sensitive information such as password. Please use the -e and a password to encrypt files"
   echo
   echo "	${bold}-f${default} ${underline}file path with mail's body${default}, ${bold}--file${default} ${underline}file path with mail's body${default}"
   echo
@@ -100,6 +104,30 @@ log()
   echo "$@" 1>&2
 }
 
+# Function to encrypt or decrypt sensitive data
+encyrpt_decrypt()
+{
+  # If encryption is set the secure sensitive information
+  if [ "$1" = "encrypt" ]; then
+    if ! openssl enc -aes-256-cbc -salt -in ~/.sendMail/userinfo -out ~/.sendMail/userinfo.enc -k "$ENCRYPT_PASSWORD" -pbkdf2 -iter 100000; then
+      log "${redlabel}[ERROR]${default} Sensitive data was not encrypted."
+      return 1
+    fi
+
+    log "${greenlabel}[SUCCESS]${default} Sensitive data was encrypted"
+    rm ~/.sendMail/userinfo
+  else
+    if ! openssl enc -aes-256-cbc -d -in ~/.sendMail/userinfo.enc -out ~/.sendMail/userinfo -k "$ENCRYPT_PASSWORD" -pbkdf2 -iter 100000; then
+      log "${redlabel}[ERROR]${default} Sensitive data was not decrypted."
+      return 1
+    fi
+
+    log "${greenlabel}[SUCCESS]${default} Sensitive data was encrypted"
+  fi
+
+  return 0
+}
+
 # Reconfigure user's email configurations for sendMail
 reConfigureSendMail()
 {
@@ -132,8 +160,6 @@ sendEmail()
   if [ "$receiversNumber" -gt 0 ]; then
     receivers=$(echo "$3" | sed 's/\ //g' | sed 's/^/--mail-rcpt\ "/' | sed 's/$/"/g' | sed 's/,/"\ --mail-rcpt\ "/g')
   fi
-  #receivers=$(echo $receivers | tr -d \'\")
-  #echo "$receivers"
 
   # Intentionally disable word splitting for $receivers argument
   # shellcheck disable=2086
@@ -156,7 +182,7 @@ if [ ! -d ~/.sendMail ]; then
 fi
 
 # If there is no : after a letter it means the specific letter has no argument, if it has :: it means the particular has optional, and a : has required argument.
-OPTIONS=$(getopt -o a:cdf:hm:p:rs:t:x --long account:,configure,delete,file:,help,message:,password:,reconfigure,subject:,to:,send -n 'sendMail' -- "$@")
+OPTIONS=$(getopt -o a:cde:f:hm:p:rs:t:x --long account:,configure,delete,encryption:,file:,help,message:,password:,reconfigure,subject:,to:,send -n 'sendMail' -- "$@")
 eval set -- "$OPTIONS"
 while true; do
   case "$1" in
@@ -164,6 +190,7 @@ while true; do
     -a|--account) echo "username:$2" >> ~/.sendMail/userinfo; shift 2;;
     -p|--password) echo "password:$2" >> ~/.sendMail/userinfo; shift 2;;
     -d|--delete) DELETE=true; shift;;
+    -e|--encryption) ENCRYPT=true; ENCRYPT_PASSWORD="$2"; shift 2;;
     #-f|--file) FILE="$2"; shift;;
     -h|--help) help_info; shift;;
     -m|--message) MESSAGE="$2"; shift 2;;
@@ -175,10 +202,22 @@ while true; do
   esac
 done
 
+if [ "$ENCRYPT" ] && [ ! -f ~/.sendMail/userinfo.enc ] ; then
+  if ! encyrpt_decrypt "encrypt"; then
+    return 0
+  fi
+fi
+
 if [ "$SEND" ]; then
-  
+
+  if [ -f ~/.sendMail/userinfo.enc ] ; then
+    if ! encyrpt_decrypt "decrypt"; then
+      return 0
+    fi
+  fi 
+ 
   # Check if user was configured before sending email
-  if [ ! -f ~/.sendMail/userinfo ]; then
+  if [ ! -f ~/.sendMail/userinfo ] && [ ! -f ~/.sendMail/userinfo.enc ]; then
     log "${redlabel}[ERROR]${default} Seems like a user was not configured!"
     log "${yellowlabel}[INFO]${default} Please run sendMail with -c file to configure"
     log "${yellowlabel}[INFO]${default} Additionally, you have to provide -a and -p arguments for account name and password, repsectively"
@@ -207,6 +246,11 @@ if [ "$SEND" ]; then
   # Remove hidden files
   if [ "$DELETE" ]; then
     rm "$MESSAGE_FILE_PATH"
+  fi
+
+  # Delete plan sensitive info
+  if [ "$ENCRYPT" ]; then
+    rm ~/.sendMail/userinfo
   fi
 fi
 
