Add more checks to avoid error

diff --git a/sendMail b/sendMail
--- a/sendMail
+++ b/sendMail
@@ -4,6 +4,9 @@
 bold=$(tput bold)
 underline=$(tput smul)
 default=$(tput sgr0)
+greenlabel=$(tput setab 2)
+redlabel=$(tput setab 1)
+yellowlabel=$(tput setab 3)
 
 help_info()
 {
@@ -92,22 +95,19 @@ reConfigureSendMail()
 
 # Send email
 # $3 the receiver of this email
-sendMail()
+sendEmail()
 {
-  curl --url 'smtps://smtp.gmail.com:465' \
+  if ! curl --url 'smtps://smtp.gmail.com:465' \
+    --silent \
     --ssl-reqd \
     --mail-from "$1" \
     --mail-rcpt "$3" \
     --user "$1:$2" \
-    -T ~/.mail_sendMail
-}
+    -T ~/.mail_sendMail; then
+    return 1
+  fi
 
-# If configuration flag is selected, check if account and password where given
-checkConfigurations()
-{
-  #if [ -z $(grep username ~/.userinfo_sendMail) ]; then
-  #fi
-  echo Under constructions
+  return 0
 }
 
 # If there is no : after a letter it means the specific letter has no argument, if it has :: it means the particular has optional, and a : has required argument.
@@ -116,22 +116,30 @@ eval set -- "$OPTIONS"
 while true; do
   case "$1" in
     -a|--account) echo "username:$2" >> ~/.userinfo_sendMail; shift 2;;
+    -p|--password) echo "password:$2" >> ~/.userinfo_sendMail; shift 2;;
     #-c|--configure) CONFIGURED=true; shift;;
     #-f|--file) FILE="$2"; shift;;
     -h|--help) help_info; shift;;
     -m|--message) MESSAGE="$2"; shift 2;;
-    -p|--password) echo "password:$2" >> ~/.userinfo_sendMail; shift 2;;
     -r|--reconfigure) reConfigureSendMail; shift;;
     -s|--subject) SUBJECT="$2"; shift 2;;
     -t|--to) TO="$2"; shift 2;;
     -x|--send) SEND=true; shift;;
     --) shift; break;;
-    *) >&2 echo "Wrong command line argument, please try again."; exit 1;;
+    *) >&2 log "${redlabel}[ERROR]${default} Wrong command line argument, please try again."; exit 1;;
   esac
 done
 
 if [ "$SEND" ]; then
   
+  # Check if user was configured before sending email
+  if [ ! -f ~/.userinfo_sendMail ]; then
+    log "${redlabel}[ERROR]${default} Seems like a user was not configured!"
+    log "${yellowlabel}[INFO]${default} Please run sendMail with -c file to configure"
+    log "${yellowlabel}[INFO]${default} Additionally, you have to provide -a and -p arguments for account name and password, repsectively"
+    exit
+  fi
+
   # Get user's info
   FROM="$(grep username ~/.userinfo_sendMail | cut -d':' -f2)"
   PASS="$(grep password ~/.userinfo_sendMail | cut -d':' -f2)"
@@ -140,7 +148,13 @@ if [ "$SEND" ]; then
   printf "From: %s\nTo: %s\nSubject: %s\n\n%s" "$FROM" "$TO" "$SUBJECT" "$MESSAGE" > ~/.mail_sendMail
   
   # Send mail
-  sendMail "$FROM" "$PASS" "$TO"
+  if ! sendEmail "$FROM" "$PASS" "$TO"; then
+    log "${redlabel}[ERROR]${default} Something went wrong and the mail was not send"
+    log "${yellowlabel}[INFO]${default} Please contact with the authors of this tool"
+    exit
+  fi
+
+  log "${greenlabel}[SUCCESS]${default} Mail was delivered to $TO successfully!"
 
   # Remove hidden files
   rm ~/.mail_sendMail
